apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
      - name: server
        image: 673536620341.dkr.ecr.us-east-1.amazonaws.com/container-migration
        ports:
        - containerPort: 9555
        env:
        - name: PORT
          value: "9555"
      imagePullSecrets:
      - name: container-migration
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
  - name: grpc
    port: 9555
    targetPort: 9555
