apiVersion: apps/v1
kind: Deployment
metadata:
  name: feservice
spec:
  selector:
    matchLabels:
      app: feservice
  template:
    metadata:
      labels:
        app: feservice
    spec:
      containers:
      - name: server
        image: 673536620341.dkr.ecr.us-east-1.amazonaws.com/container-migration
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
      imagePullSecrets:
      - name: container-migration
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
  - name: grpc
    port: 3000
    targetPort: 3000
