apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: portfolio
  namespace: ob3
spec:
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: 673536620341.dkr.ecr.us-east-1.amazonaws.com/container-migration:v2
  selector:
    matchLabels:
      app: apache
  replicas: 1
  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause: { duration: 10m }
